config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  
  resources :groups, only: [:index, :show, :new, :create, :destroy] do
    resources :entities, only: [:new, :create, :destroy]
  end
  resources :users
  
  devise_scope :user do
    authenticated :user do
      root to: 'groups#index', as: :authenticated_root
    end

    unauthenticated do
      root to: 'first_page#index'
    end
  end
end

app/models/entity.rb
class Entity < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: 'users_id'
  belongs_to :group

  validates :name, presence: true
  validates :amount, numericality: { greater_than_or_equal_to: 0 }
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  before_action :set_entity, only: %i[show edit update destroy]

  # GET /entities or /entities.json
  def index
    @entities = Entity.all
  end

  # GET /entities/1 or /entities/1.json
  def show; end

  # GET /entities/new
  def new
    @entity = Entity.new
  end

  # GET /entities/1/edit
  def edit; end

  # POST /entities or /entities.json
  def create
    @group = Group.find(params[:group_id])
    @entity = @group.entities.new(entity_params)
    @entity.user = current_user
    if @entity.save
      redirect_to group_path(@group), notice: 'Transaction processed successfully.'
    else
      render :new
    end
  end

  # PATCH/PUT /entities/1 or /entities/1.json
  def update
    respond_to do |format|
      if @entity.update(entity_params)
        format.html { redirect_to entity_url(@entity), notice: 'Entity was successfully updated.' }
        format.json { render :show, status: :ok, location: @entity }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @entity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entities/1 or /entities/1.json
  def destroy
    @entity.destroy

    respond_to do |format|
      format.html { redirect_to entities_url, notice: 'Transaction successfully removed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_entity
    @entity = Entity.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def entity_params
    params.require(:entity).permit(:name, :amount, :group_id)
  end
end

app/views/entities/new.html.erb
<div class="container main-color d-flex flex-column align-items-center rounded">

  `<h1>New Transaction</h1>

  <%= form_with model: @entity, url: group_entities_path(params[:group_id]) do |form| %>
    <div class="field font-light mb-3">
      <%= form.label :name %><br />
      <%= form.text_field :name, class: "form-control", autofocus: true, placeholder: "Enter the name here" %>
    </div>

    <div class="field font-light mb-3">
      <%= form.label :amount %><br />
      <%= form.number_field :amount, class: "form-control", autofocus: true, placeholder: "$" %>
    </div>

    <div class="actions">
      <%= form.submit "Save", class: "link font-light mb-5 mt-3" %>
      
    </div>
    <%= link_to group_path(params[:group_id]) do %>
      <i class="fa-solid fa-angle-left icon-back-form mb-3"></i>
    <% end %>
  <% end %>
</div>