config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  
  resources :groups, only: [:index, :show, :new, :create, :destroy] do
    resources :entities, only: [:new, :create, :destroy]
  end
  resources :users
  
  devise_scope :user do
    authenticated :user do
      root to: 'groups#index', as: :authenticated_root
    end

    unauthenticated do
      root to: 'first_page#index'
    end
  end
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :users, class_name: 'User', foreign_key: 'users_id'
  has_many :entities

  validates :name, presence: true
  validates :icon, presence: true

  def total
    entities.sum(:amount)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[show edit update destroy]

  # GET /groups or /groups.json
  def index
    @groups = Group.where(users_id: current_user.id)
  end

  def show
    @group = Group.find(params[:id])
    @entities = @group.entities.all
    @entity = Entity.new
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit; end

  def create
    @group = Group.new(group_params)
    @group.users_id = current_user.id

    respond_to do |format|
      if @group.save
        format.html { redirect_to groups_path, notice: 'Category successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1 or /groups/1.json
  def update
    respond_to do |_format|
      if @group.update(group_params)
        redirect_to authenticated_root_path, notice: 'Group was successfully updated.'
      else
        render :edit, status: :unprocessable_entity
      end
    end
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Category successfully removed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def group_params
    params.require(:group).permit(:name, :icon, :users_id)
  end
end

app/views/groups/index.html.erb
<% if user_signed_in? %>
  <% @groups.each do |group| %>
    <div class="card d-flex m-5 p-3">
      <%= link_to group_path(group.id), class: "font-light" do %>
        <div class="d-flex align-items-center justify-content-between">
          <div class="d-flex align-items-center ms-4 me-5">
            <%= image_tag group.icon, class: "image-size m-3" %>
            <p class="font-light"><%= group.name %></p>
          </div>
          <p class="font-light ms-5">Total Amount: $<%= group.total%></p>
        </div>
      <% end %>
    </div>
  <% end %>
    
  <div class="text-center row">
    <%= link_to 'Add New Category', new_group_path, class: 'link font-light mx-auto' %>
  </div>
   
<% else %>
  <div class="sign-in-color"><%= link_to 'Sign In', new_user_session_path, class: "sign-in" %></div>
<% end%>

app/views/groups/new.html.erb
<div class="container main-color d-flex flex-column align-items-center rounded">
  <h1 class="mt-5">New Category</h1>
  <%= form_with model: @group, url: groups_path do |form| %>
    <div class="field font-light mb-3 mt-3">
      <%= form.label :name %><br />
      <%= form.text_field :name, class: "form-control", autofocus: true, placeholder: "Enter category name here" %>
    </div>

    <div class="field font-light mb-3">
      <%= form.label :photo %><br />
      <%= form.select :icon, [['cars', 'cars.jpg'], ['outings', 'outings.jpg'],['groceries', 'groceries.jpg'], ['health care', 'health-care.jpg'], ['pets', 'pets.jpg']], class: "link2", autofocus: true %>
    </div>
    <div class="d-flex flex-column">
      <%= form.submit "Save", class: "link font-light mb-5 mt-3" %>
      <%= link_to groups_path do %>
        <i class="fa-solid fa-angle-left icon-back-form mb-3"></i>
      <% end %>
    </div>
  <% end %>
</div>

app/views/groups/show.html.erb
<div class="card m-5">
  <div class="card-body d-flex align-items-center justify-content-between">
    <div class="d-flex align-items-center ms-5">
      <%= image_tag @group.icon, class: "image-size m-3" %>
      <p class="font-light ms-3"><%= @group.name %></p>
    </div>

    <p class="font-light me-3">$<%= @group.total %></p>

  </div>
</div>

<% if @entities.empty? %>
  <p class="font-light text-center">No Transactions made</p>
<% else %>
  <% @entities.each do |entity| %>
    <div class="card m-5">
      <div class="card-body d-flex align-items-center justify-content-between">
        <div class="d-flex align-items-center ms-5">
          <%= image_tag @group.icon, class: "image-size m-3" %>
          <p class="font-light ms-3"><%= entity.name %></p>
        </div>
        <p class="font-light me-3">Amount: $<%= entity.amount%></p>
      </div>
    </div>
  <% end %>
<% end %>

<div class="row">
  <%= link_to "Add new Transaction", new_group_entity_path(group_id: @group.id), class:"link font-light" %>
</div>