config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  
  resources :groups, only: [:index, :show, :new, :create, :destroy] do
    resources :entities, only: [:new, :create, :destroy]
  end
  resources :users
  
  devise_scope :user do
    authenticated :user do
      root to: 'groups#index', as: :authenticated_root
    end

    unauthenticated do
      root to: 'first_page#index'
    end
  end
end

app/views/layouts/_nav.html.erb
<div class="nav navbar main-color">
  <% if  params[:action].present? %>
    <%= link_to groups_path do %>
      <i class="fa-solid fa-arrow-left text-white ms-3"></i>
    <%end %>
  <%else%>
    <%= link_to :back do %>
      <i class="fa-solid fa-arrow-left text-white ms-3"></i>
    <%end %>
  <%end%>
  <%p params%>
  <% if params[:action] == 'show'%>
    <h2 class="text-white ms-4">transactions</h2>
  <% else%>
    <h2 class="text-white ms-4">Category</h2>
  <%end%>
  <%= button_to "Log out", destroy_user_session_path, class: "btn bg-blue text-white", method: :delete, data: { turbo: false } %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Savvy</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <script src="https://kit.fontawesome.com/8a3c9493da.js" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  </head>

  <body>
  <% if user_signed_in? || current_page?(new_user_session_path) || current_page?(new_user_registration_path) %>
      <%= render partial: 'layouts/nav' %>
    <% end %>
    <p class="notice font-light"><%= notice %></p>
    <%= yield %>
  </body>
</html>